### ISSUE TITLE
[CRASH] table remembered_server has no column named pass

### ISSUE THREAD

**Issue by ildar** [nicolasbrailo/VlcFreemote#1]
```
01-13 14:15:28.014  4099  4099 E AndroidRuntime: FATAL EXCEPTION: main
01-13 14:15:28.014  4099  4099 E AndroidRuntime: Process: com.nicolasbrailo.vlcfreemote, PID: 4099
01-13 14:15:28.014  4099  4099 E AndroidRuntime: android.database.sqlite.SQLiteException: table remembered_server has no column named pass (code 1): , while compiling: REPLACE INTO remembered_server( ip,port,display_name,pass,last_path, last_used ) VALUES ( ?, ?, ?, ?, ?, 1)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1658)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at com.nicolasbrailo.vlcfreemote.local_settings.LocalSettings.run(LocalSettings.java:47)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at com.nicolasbrailo.vlcfreemote.local_settings.RememberedServers.rememberServer(RememberedServers.java:78)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at com.nicolasbrailo.vlcfreemote.ServerSelectView$3.onClick(ServerSelectView.java:202)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
01-13 14:15:28.014  4099  4099 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6130)
```

**Comment by nicolasbrailo** [comment]
Hello @ildar. Thank you so much for taking the time to report this problem. It's a bug I introduced in the last release, sorry for the problems.

There is a fix in place. I had a problem with the repo and had to take it offline for the moment. I'm hoping I can spend some time later this week to fix it and publish an update.

**Comment by nicolasbrailo** [comment]
Once fdroid updates, this issue will be fixed

**Comment by ildar** [comment]
Thanks
