### ISSUE TITLE
[CRASH] RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by ildar** [nicolasbrailo/VlcFreemote#7]
```
07-24 01:10:25.955 11346 11371 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
07-24 01:10:25.955 11346 11371 E AndroidRuntime: Process: com.nicolasbrailo.vlcfreemote, PID: 11346
07-24 01:10:25.955 11346 11371 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:200)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:114)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.app.Dialog.<init>(Dialog.java:122)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.app.AlertDialog.<init>(AlertDialog.java:200)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.app.AlertDialog$Builder.create(AlertDialog.java:1086)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.MainActivity.onAppBug(MainActivity.java:340)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.MainActivity.onVlcStatusFetchError(MainActivity.java:282)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.vlc_connector.RemoteVlc.onVlcStatusFetchError(RemoteVlc.java:117)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.vlc_connector.VlcCommand_ReturnsVlcStatus$1$1.parseValue(VlcCommand_ReturnsVlcStatus.java:50)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.vlc_connector.VlcCommand_ReturnsVlcStatus$1$1.parseValue(VlcCommand_ReturnsVlcStatus.java:42)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.XmlObjectReader.xmlParseImpl(XmlObjectReader.java:41)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.XmlMogrifier.doInBackground(XmlMogrifier.java:80)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.XmlMogrifier.doInBackground(XmlMogrifier.java:20)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 01:10:25.955 11346 11371 E AndroidRuntime: 	... 4 more
```

**Comment by nicolasbrailo** [comment]
I wonder if something changed in the format that the app wasn't able to parse. @ildar if by any chance you can get a copy of the XML that caused this crash, I'd love to see it.

**Comment by ildar** [comment]
XML? What's the URL to fetch? I can try next time I see it.

**Comment by nicolasbrailo** [comment]
Thanks @ildar . This *shouldn't* crash anymore now, but there will still be an action that doesn't work (the crash was happening when reporting an error). Unfortunately I don't know which action that was. If you do find an action which doesn't crash; the way I usually capture the XML of an action is by opening the player html interface (just open in your browser the same URL you configured VlcFreemote with to connect to your VLC instance) and then performing the same action in the html interface while capturing the network messages in Firefox.

I understand if that's too much work for a bug that rarely occurs.
