### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by drmdshahid** [nicolasbrailo/VlcFreemote#8]
A fatal error was found when connecting to server 192.168.1.11:8080. This typically means there is a bug in the application.Please submit a bug report. Additional information: Fatal error: the default VlcPath (/) is not valid on your setup. Please submit a bug report.com.nicolasbrailo.vlcfreemote.model.VlcPath$VlcPath_ApplicationError: Fatal error: the default VlcPath (/) is not valid on your setup. Please submit a bug report.
	at com.nicolasbrailo.vlcfreemote.model.VlcPath$2.onContentError(VlcPath.java:150)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.Cmd_DirList$1.onHttpNotOkResponse(Cmd_DirList.java:56)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.Cmd_DirList$1.onResponse(Cmd_DirList.java:64)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.Wget.onPostExecute(Wget.java:100)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.Wget.onPostExecute(Wget.java:14)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by nicolasbrailo** [comment]
@drmdshahid interesting, thanks for the report! The app assumes that '/' is a valid starting path, and so far it seemed to work fine for both Windows and Linux. Where are you running your VLC server that / is not a valid path? Is it really that / is not valid, or is it an access-denied kind of thing?

**Comment by drmdshahid** [comment]
im running VLC server on windows 10.

**Comment by astrovan14** [comment]
I've gotten this same error running windows 10. It doesn't hinder my use of the playlist, seek, or media controls, but it shows an annoying popup that gets in the way. The browse function doesn't work, but I would be more than okay with that feature able to be toggled if I wouldn't have to see that error popup every time the app opens.
I am willing to help provide more info if needed.

**Comment by nicolasbrailo** [comment]
Thanks for reporting @astrovan14 

I think the fix should be simple. In https://github.com/nicolasbrailo/VlcFreemote/blob/master/app/src/main/java/com/nicolasbrailo/vlcfreemote/model/VlcPath.java#L143 we should check if the current path is already the default path, and if it is then try an alt-default-path (eg C:?). This should also be a one-time only thing, as after finding a path that works the app will remember it for the next time.

Unfortunately I'm quite short on time (seeing how this simple bug has been open for such a long time...) so it's unlikely I'll be able to give this a try. I also have no Windows machines to test the alt-default-path anyway, which means the only realistic option to get this fixed quickly will be a PR :)
