### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ShironCat** [nicolasbrailo/VlcFreemote#9]
A fatal error was found when connecting to server 192.168.0.2:8080. This typically means there is a bug in the application.Please submit a bug report. Additional information: Fatal error: the default VlcPath (/) is not valid on your setup. Please submit a bug report.com.nicolasbrailo.vlcfreemote.model.VlcPath$VlcPath_ApplicationError: Fatal error: the default VlcPath (/) is not valid on your setup. Please submit a bug report.
	at com.nicolasbrailo.vlcfreemote.model.VlcPath$2.onContentError(VlcPath.java:150)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.Cmd_DirList$1.onHttpNotOkResponse(Cmd_DirList.java:56)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.Cmd_DirList$1.onResponse(Cmd_DirList.java:64)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.Wget.onPostExecute(Wget.java:100)
	at com.nicolasbrailo.vlcfreemote.vlc_connector.http_utils.Wget.onPostExecute(Wget.java:14)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:240)
	at android.app.ActivityThread.main(ActivityThread.java:8000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by nicolasbrailo** [comment]
Thanks for reporting @ShironCat. This is the same problem as reported in issue #8. There's a fix planned, but no unfortunately no ETA yet (PRs are welcome though!)
